spring:
  profiles:
    active: prod

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: Djangobbs

---
spring:
  profiles: dev

server:
  port: 8080

---
spring:
  profiles: test

server:
  port: 8081

---
spring:
  profiles: prod

server:
  port: 8082

